import pytest
from unittest.mock import MagicMock
from agent.framing import validate_framing, generate_framing, compose_email_body

def test_validate_framing_valid():
    text = "Hello, here is an update. Please let me know if you have questions."
    assert validate_framing(text) is True

def test_validate_framing_too_short():
    assert validate_framing("Hi.") is False

def test_validate_framing_too_long():
    text = "a" * 201
    assert validate_framing(text) is False

def test_validate_framing_prohibited_words():
    assert validate_framing("This was generated by pydantic.") is False
    assert validate_framing("I am an AI bot.") is False
    assert validate_framing("The llm said yes.") is False

def test_validate_framing_prohibited_chars():
    assert validate_framing("Here is a *bold* statement.") is False
    assert validate_framing("Look at this json { key: value }") is False

def test_validate_framing_double_newline():
    assert validate_framing("Hello.\n\nHow are you?") is False

def test_validate_framing_lists():
    assert validate_framing("- Point 1\n- Point 2") is False
    assert validate_framing("1. Point 1") is False

def test_validate_framing_uncertainty():
    assert validate_framing("I think we should meet then.") is False
    assert validate_framing("Perhaps this time works.") is False

def test_generate_framing_success(mocker):
    mock_groq = mocker.patch("agent.framing.Groq")
    mock_client = MagicMock()
    mock_groq.return_value = mock_client
    
    mock_response = MagicMock()
    mock_response.choices[0].message.content = "   Valid framing here.   "
    mock_client.chat.completions.create.return_value = mock_response

    result = generate_framing("Prompt")
    assert result == "Valid framing here."

def test_generate_framing_failure(mocker):
    mock_groq = mocker.patch("agent.framing.Groq", side_effect=Exception("API Error"))
    result = generate_framing("Prompt")
    assert result is None

def test_compose_email_body_valid_framing(mocker):
    mocker.patch("agent.framing.generate_framing", return_value="Here is your proposal.")
    mocker.patch("agent.framing.validate_framing", return_value=True)

    body = compose_email_body(
        "slot_proposal",
        "Prompt",
        "Core: {date}",
        {"date": "2025-01-01"}
    )
    
    assert body == "Here is your proposal.\n\nCore: 2025-01-01"

def test_compose_email_body_booking_confirmation(mocker):
    mocker.patch("agent.framing.generate_framing", return_value="Have a great meeting.")
    mocker.patch("agent.framing.validate_framing", return_value=True)

    body = compose_email_body(
        "booking_confirmation",
        "Prompt",
        "Core: {date}",
        {"date": "2025-01-01"}
    )
    
    assert body == "Core: 2025-01-01\n\nHave a great meeting."

def test_compose_email_body_no_framing(mocker):
    mocker.patch("agent.framing.generate_framing", return_value=None)
    
    body = compose_email_body(
        "slot_proposal",
        "Prompt",
        "Core: {date}",
        {"date": "2025-01-01"}
    )
    
    assert body == "Core: 2025-01-01"

def test_compose_email_body_invalid_framing(mocker):
    mocker.patch("agent.framing.generate_framing", return_value="I am an AI.")
    mocker.patch("agent.framing.validate_framing", return_value=False)

    body = compose_email_body(
        "slot_proposal",
        "Prompt",
        "Core: {date}",
        {"date": "2025-01-01"}
    )
    
    assert body == "Core: 2025-01-01"

def test_compose_email_body_missing_var(mocker):
    mocker.patch("agent.framing.generate_framing", return_value=None)

    body = compose_email_body(
        "slot_proposal",
        "Prompt",
        "Core: {date} and {time}",
        {"date": "2025-01-01"}
    )
    
    assert body == "Core: {date} and {time}"
